version: '3'
services:
  client:
    image: client:latest
    ports:
      - '5000:5000'
    stdin_open: true
    depends_on:
      - server
    networks:
      - design-flow

  server:
    image: server:latest
    ports:
      - '3000:3000'
    depends_on:
      - mongo
    networks:
      - design-flow

  mongo:
    image: mongo:latest
    ports:
      - '27017:27017'
    networks:
      - design-flow
    volumes:
      - mongo-data:/data/db

networks:
  design-flow:
    driver: bridge

volumes:
  mongo-data:
    driver: local
