apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    role: client
    env: demo
  name: client
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 25%
  selector:
    matchLabels:
      role: client
  template:
    metadata:
      labels:
        role: client
    spec:
      containers:
        - name: client
          image: thetharz/design-flow-client:latest
          imagePullPolicy: Always
          env:
            - name: REACT_APP_BACKEND_URL
              value: 'http://server:5000'
          ports:
            - containerPort: 3000

---
apiVersion: v1
kind: Service
metadata:
  name: clientservice
spec:
  selector:
    role: client
  type: NodePort
  ports:
    - port: 3000
      targetPort: 3000
      nodePort: 30100
      protocol: TCP
