apiVersion: apps/v1
kind: Deployment
metadata:
  name: server
  labels:
    app: server
    role: server
    env: demo
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 25%
  selector:
    matchLabels:
      app: server
      role: server
      env: demo
  template:
    metadata:
      labels:
        app: server
        role: server
        env: demo
    spec:
      containers:
        - name: server
          image: thetharz/design-flow-server:latest
          imagePullPolicy: Always
          env:
            - name: MONGO_CONN_STR
              value: mongo://mongo-service:27017/designflow?directConnection=true
            - name: MONGO_USERNAME
              valueFrom:
                secretKeyRef:
                  name: mongo-secret
                  key: mongo-user
            - name: MONGO_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mongo-secret
                  key: mongo-password
          ports:
            - containerPort: 5000
          livenessProbe:
            httpGet:
              path: /ok
              port: 5000
            initialDelaySeconds: 2
            periodSeconds: 5
          readinessProbe:
            httpGet:
              path: /ok
              port: 5000
            initialDelaySeconds: 5
            periodSeconds: 5
            successThreshold: 1

---
apiVersion: v1
kind: Service
metadata:
  name: serverservice
spec:
  selector:
    app: server
    role: server
    env: demo
  type: ClusterIP
  ports:
    - port: 5000
      protocol: TCP
