apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: client
  name: client
spec:
  replicas: 1
  selector:
    matchLabels:
      app: client
  template:
    metadata:
      labels:
        app: client
    spec:
      containers:
        - image: thetharz/design-flow-client:latest
          name: client
          ports:
            - containerPort: 3000

---
apiVersion: v1
kind: Service
metadata:
  name: clientservice
spec:
  selector:
    app: client
  type: NodePort
  ports:
    - port: 3000
      targetPort: 3000
      nodePort: 30100
