apiVersion: apps/v1
kind: Deployment
metadata:
  name: server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: server
  template:
    metadata:
      labels:
        app: server
    spec:
      containers:
        - name: server
          image: thetharz/design-flow-server:latest
          ports:
            - containerPort: 5000

---
apiVersion: v1
kind: Service
metadata:
  name: serverservice
spec:
  selector:
    app: server
  type: ClusterIP
  ports:
    - port: 5000
      targetPort: 5000
